<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ScnHttpCache\Module'          => __DIR__ . '/src/ScnHttpCache/Module.php',
    'ScnHttpCache\View\Helper\Esi' => __DIR__ . '/src/ScnHttpCache/View/Helper/Esi.php',
);