<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ScnHttpCache\Module'                                        => __DIR__ . '/src/ScnHttpCache/Module.php',
    'ScnHttpCache\Service\EsiApplicationConfigProvider'          => __DIR__ . '/src/ScnHttpCache/Service/EsiApplicationConfigProvider.php',
    'ScnHttpCache\Service\EsiApplicationConfigProviderAbstract'  => __DIR__ . '/src/ScnHttpCache/Service/EsiApplicationConfigProviderAbstract.php',
    'ScnHttpCache\Service\EsiApplicationConfigProviderInterface' => __DIR__ . '/src/ScnHttpCache/Service/EsiApplicationConfigProviderInterface.php',
    'ScnHttpCache\Service\EsiViewHelperFactory'                  => __DIR__ . '/src/ScnHttpCache/Service/EsiViewHelperFactory.php',
    'ScnHttpCache\Service\Exception\ExceptionInterface'          => __DIR__ . '/src/ScnHttpCache/Service/Exception/ExceptionInterface.php',
    'ScnHttpCache\Service\Exception\RuntimeException'            => __DIR__ . '/src/ScnHttpCache/Service/Exception/RuntimeException.php',
    'ScnHttpCache\View\Exception\ExceptionInterface'             => __DIR__ . '/src/ScnHttpCache/View/Exception/ExceptionInterface.php',
    'ScnHttpCache\View\Exception\RuntimeException'               => __DIR__ . '/src/ScnHttpCache/View/Exception/RuntimeException.php',
    'ScnHttpCache\View\Helper\Esi'                               => __DIR__ . '/src/ScnHttpCache/View/Helper/Esi.php',
);